# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a3ef831c-2b2b-4d29-b26e-684289ab0ef7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a3ef831c-2b2b-4d29-b26e-684289ab0ef7".device = "/dev/disk/by-uuid/a3ef831c-2b2b-4d29-b26e-684289ab0ef7";
  boot.initrd.luks.devices."luks-a3ef831c-2b2b-4d29-b26e-684289ab0ef7".crypttabExtraOpts = [ "tpm2-device=auto" ];

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B768-C175";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-6b14e3c8-d0d7-45a8-ac75-92440d3f3964"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  boot.initrd.luks.devices."luks-6b14e3c8-d0d7-45a8-ac75-92440d3f3964".device = "/dev/disk/by-uuid/6b14e3c8-d0d7-45a8-ac75-92440d3f3964";
  boot.initrd.luks.devices."luks-6b14e3c8-d0d7-45a8-ac75-92440d3f3964".crypttabExtraOpts = [ "tpm2-device=auto" ];
}
