# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-92560649-e630-4a01-a7bf-8ce4af613ac0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-92560649-e630-4a01-a7bf-8ce4af613ac0".device = "/dev/disk/by-uuid/92560649-e630-4a01-a7bf-8ce4af613ac0";
  boot.initrd.luks.devices."luks-92560649-e630-4a01-a7bf-8ce4af613ac0".crypttabExtraOpts = [ "tpm2-device=auto" ];

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/571B-0982";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-40c5ac48-ebaa-4f96-97c1-a6aee16fa448"; }
    ];

  boot.initrd.luks.devices."luks-40c5ac48-ebaa-4f96-97c1-a6aee16fa448".device = "/dev/disk/by-uuid/40c5ac48-ebaa-4f96-97c1-a6aee16fa448";
  boot.initrd.luks.devices."luks-40c5ac48-ebaa-4f96-97c1-a6aee16fa448".crypttabExtraOpts = [ "tpm2-device=auto" ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
