set-option -g mouse on

bind -n A-Right next-window
bind -n A-Left previous-window
bind -n C-A-Right new-window -c '#{pane_current_path}'

bind-key S-Up select-pane -U
bind-key C-Down select-pane -D
bind-key C-Left select-pane -L
bind-key C-Right select-pane -R
bind-key -n C-S-Down split-window -v -c '#{pane_current_path}'
bind-key -n C-S-Right split-window -h -c '#{pane_current_path}'
