export EDITOR='vim';
export TERM='xterm-256color';

if [ -e ~/.nix-profile/etc/profile.d/nix.sh ]; then
  . ~/.nix-profile/etc/profile.d/nix.sh;
fi

if [ -e ~/.env ]; then
  . ~/.env;
fi

# Autocomplete for various utilities
#command -v hass-cli &>/dev/null && source <(hass-cli completion zsh);
command -v helm &>/dev/null && source <(helm completion zsh);
command -v kubectl &>/dev/null && source <(kubectl completion zsh);
command -v minikube &>/dev/null && source <(minikube completion zsh);
command -v gh &>/dev/null && source <(gh completion --shell zsh);
command -v rustup &>/dev/null && rustup completions zsh > ~/.zfunc/_rustup;
command -v cue &>/dev/null && source <(cue completion zsh);
command -v npm &>/dev/null && source <(npm completion zsh);
command -v humioctl &>/dev/null && source <(humioctl completion zsh);
command -v fluxctl &>/dev/null && source <(fluxctl completion zsh);

# direnv hook
eval "$(direnv hook zsh)";

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
'';
