export EDITOR='vim';
export TERM='xterm-256color';
export THEFUCK_PRIORITY='no_command=0';

if [ -e ~/.nix-profile/etc/profile.d/nix.sh ]; then
  USER=${USER:-root} . ~/.nix-profile/etc/profile.d/nix.sh;
fi

if [ -e ~/.env ]; then
  . ~/.env;
fi

# Autocomplete for various utilities
#command -v hass-cli &>/dev/null && source <(hass-cli completion zsh);
command -v helm &>/dev/null && source <(helm completion zsh);
command -v kubectl &>/dev/null && source <(kubectl completion zsh);
command -v minikube &>/dev/null && source <(minikube completion zsh);
command -v gh &>/dev/null && source <(gh completion --shell zsh);
command -v npm &>/dev/null && source <(npm completion zsh);

# direnv hook
eval "$(direnv hook zsh)";

# the fuck alias
eval $(thefuck --alias)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh;
