export EDITOR='vim';
export TERM='xterm-256color';
export PATH=${PATH}:${HOME}/.local/bin;

if [ -z "${NIX_PROFILES}" ]; then
  if [ -f /etc/alpine-release ]; then
    export USER=${USER:-root};
  elif [ -n "${TERMUX_VERSION}" ]; then
    export GC_NPROCS=1;
    export USER=${USER:-null};
  fi  
  . ${HOME}/.nix-profile/etc/profile.d/nix.sh;
fi

if [ -e ~/.env ]; then
  . ~/.env;
fi

# keybindings
bindkey "^[[1;5C" forward-word;
bindkey "^[[1;5D" backward-word;
bindkey "''${key[Up]}" up-line-or-search;

# direnv hook
eval "$(direnv hook zsh)";

# exa aliases
alias ls='exa'; # just replace ls by exa and allow all other exa arguments
alias l='ls -lbF'; # list, size, type
alias ll='ls -la'; # long, all
alias llm='ll --sort=modified'; # list, long, sort by modification date
alias la='ls -lbhHigUmuSa'; # all list
alias lx='ls -lbhHigUmuSa@'; # all list and extended
alias tree='exa --tree'; # tree view
alias lS='exa -1'; # one column by just names

# other aliases
alias open='xdg-open';
alias slugify='rename "s/ /_/g; s/_/-/g; s/[^a-zA-Z0-9.-]//g; y/A-Z/a-z/"';
