export EDITOR='vim';
export TERM='xterm-256color';
export PATH=${PATH}:${HOME}/.local/bin;

if [ -z "${NIX_PROFILES}" ]; then
  if [ -f /etc/alpine-release ]; then
    export USER=${USER:-root};
  elif [ -n "${TERMUX_VERSION}" ]; then
    export GC_NPROCS=1;
    export USER=${USER:-null};
  fi  
  . ${HOME}/.nix-profile/etc/profile.d/nix.sh;
fi

if [ -e ~/.env ]; then
  set -a;
  source ~/.env;
  set +a;
fi

# keybindings
bindkey "^[[1;5C" forward-word;
bindkey "^[[1;5D" backward-word;
bindkey "''${key[Up]}" up-line-or-search;

# zsh_codex plugin keybinding and configuration
zle -N create_completion;
bindkey '^X' create_completion;
if [[ -n "$OPENAI_API_KEY" ]]; then
  sed -i "/^\[openai_service\]/,/^\[/ s/^api_key *= *.*/api_key = $OPENAI_API_KEY/" ~/.config/zsh_codex.ini
fi

# alias function for goose
o() { goose run -st "$*"; }
